### ISSUE TITLE
Version v3.0.9 not working

### ISSUE THREAD

**Issue by Muardin** [edvordo/TabsOfAvabur#1]
Hi,

you have some bugs on lots of warnings in your code.
I fixed it on my PC, but I can't commit it.

Most important thing to let it run for me is:
line 1550: ""message" -> "message"

Here is the whole list for you:

VM19981:58 Syntax error @ "TabsOfAvabur"!
###### 

JSHINT output:
script: (W041) Use '===' to compare with '0' on line: 256 at character: 20
script: (W033) Missing semicolon on line: 695 at character: 57
script: (W069) ['scriptSettings'] is better written in dot notation on line: 792 at character: 24
script: (W018) Confusing use of '!' on line: 792 at character: 17
script: (W069) ['scriptSettings'] is better written in dot notation on line: 793 at character: 27
script: (W069) ['purge'] is better written in dot notation on line: 793 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 794 at character: 60
script: (W069) ['purge'] is better written in dot notation on line: 794 at character: 78
script: (W069) ['scriptSettings'] is better written in dot notation on line: 796 at character: 27
script: (W069) ['channel_remove'] is better written in dot notation on line: 796 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 797 at character: 69
script: (W069) ['channel_remove'] is better written in dot notation on line: 797 at character: 87
script: (W069) ['scriptSettings'] is better written in dot notation on line: 799 at character: 27
script: (W069) ['preview'] is better written in dot notation on line: 799 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 800 at character: 62
script: (W069) ['preview'] is better written in dot notation on line: 800 at character: 80
script: (W069) ['scriptSettings'] is better written in dot notation on line: 802 at character: 27
script: (W069) ['preview_reset'] is better written in dot notation on line: 802 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 803 at character: 68
script: (W069) ['preview_reset'] is better written in dot notation on line: 803 at character: 86
script: (W069) ['scriptSettings'] is better written in dot notation on line: 805 at character: 27
script: (W069) ['group_wires'] is better written in dot notation on line: 805 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 806 at character: 66
script: (W069) ['group_wires'] is better written in dot notation on line: 806 at character: 84
script: (W069) ['scriptSettings'] is better written in dot notation on line: 808 at character: 27
script: (W069) ['at_username'] is better written in dot notation on line: 808 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 809 at character: 66
script: (W069) ['at_username'] is better written in dot notation on line: 809 at character: 84
script: (W069) ['scriptSettings'] is better written in dot notation on line: 811 at character: 27
script: (W069) ['join_channel_link'] is better written in dot notation on line: 811 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 812 at character: 72
script: (W069) ['join_channel_link'] is better written in dot notation on line: 812 at character: 90
script: (W069) ['scriptSettings'] is better written in dot notation on line: 814 at character: 27
script: (W069) ['auto_join'] is better written in dot notation on line: 814 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 815 at character: 64
script: (W069) ['auto_join'] is better written in dot notation on line: 815 at character: 82
script: (W069) ['scriptSettings'] is better written in dot notation on line: 817 at character: 27
script: (W069) ['profile_tooltip_nickname'] is better written in dot notation on line: 817 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 818 at character: 79
script: (W069) ['profile_tooltip_nickname'] is better written in dot notation on line: 818 at character: 97
script: (W069) ['scriptSettings'] is better written in dot notation on line: 820 at character: 27
script: (W069) ['profile_tooltip_mention'] is better written in dot notation on line: 820 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 821 at character: 78
script: (W069) ['profile_tooltip_mention'] is better written in dot notation on line: 821 at character: 96
script: (W069) ['scriptSettings'] is better written in dot notation on line: 823 at character: 27
script: (W069) ['profile_tooltip_quickscope'] is better written in dot notation on line: 823 at character: 45
script: (W069) ['scriptSettings'] is better written in dot notation on line: 824 at character: 81
script: (W069) ['profile_tooltip_quickscope'] is better written in dot notation on line: 824 at character: 99
script: (W069) ['channelsSettings'] is better written in dot notation on line: 827 at character: 23
script: (W069) ['version'] is better written in dot notation on line: 827 at character: 67
script: (W069) ['channelsSettings'] is better written in dot notation on line: 828 at character: 27
script: (W069) ['mutedChannels'] is better written in dot notation on line: 828 at character: 47
script: (W069) ['channelsSettings'] is better written in dot notation on line: 828 at character: 102
script: (W069) ['mutedChannels'] is better written in dot notation on line: 828 at character: 122
script: (W069) ['channelsSettings'] is better written in dot notation on line: 829 at character: 68
script: (W069) ['mutedChannels'] is better written in dot notation on line: 829 at character: 88
script: (W069) ['channelsSettings'] is better written in dot notation on line: 831 at character: 27
script: (W069) ['channelMerger'] is better written in dot notation on line: 831 at character: 47
script: (W069) ['channelsSettings'] is better written in dot notation on line: 832 at character: 31
script: (W069) ['channelMerger'] is better written in dot notation on line: 832 at character: 51
script: (W069) ['groups'] is better written in dot notation on line: 832 at character: 68
script: (W069) ['channelsSettings'] is better written in dot notation on line: 832 at character: 116
script: (W069) ['channelMerger'] is better written in dot notation on line: 832 at character: 136
script: (W069) ['groups'] is better written in dot notation on line: 832 at character: 153
script: (W069) ['channelsSettings'] is better written in dot notation on line: 833 at character: 47
script: (W069) ['channelMerger'] is better written in dot notation on line: 833 at character: 67
script: (W069) ['groups'] is better written in dot notation on line: 833 at character: 84
script: (W069) ['channelsSettings'] is better written in dot notation on line: 834 at character: 51
script: (W069) ['channelMerger'] is better written in dot notation on line: 834 at character: 71
script: (W069) ['groups'] is better written in dot notation on line: 834 at character: 88
script: (W069) ['channelsSettings'] is better written in dot notation on line: 841 at character: 31
script: (W069) ['channelMerger'] is better written in dot notation on line: 841 at character: 51
script: (W069) ['mapping'] is better written in dot notation on line: 841 at character: 68
script: (W069) ['channelsSettings'] is better written in dot notation on line: 841 at character: 110
script: (W069) ['channelMerger'] is better written in dot notation on line: 841 at character: 130
script: (W069) ['mapping'] is better written in dot notation on line: 841 at character: 147
script: (W069) ['channelsSettings'] is better written in dot notation on line: 842 at character: 80
script: (W069) ['channelMerger'] is better written in dot notation on line: 842 at character: 100
script: (W069) ['mapping'] is better written in dot notation on line: 842 at character: 117
script: (W069) ['channelsSettings'] is better written in dot notation on line: 844 at character: 31
script: (W069) ['channelMerger'] is better written in dot notation on line: 844 at character: 51
script: (W069) ['defaultChannels'] is better written in dot notation on line: 844 at character: 68
script: (W069) ['channelsSettings'] is better written in dot notation on line: 844 at character: 118
script: (W069) ['channelMerger'] is better written in dot notation on line: 844 at character: 138
script: (W069) ['defaultChannels'] is better written in dot notation on line: 844 at character: 155
script: (W069) ['channelsSettings'] is better written in dot notation on line: 845 at character: 88
script: (W069) ['channelMerger'] is better written in dot notation on line: 845 at character: 108
script: (W069) ['defaultChannels'] is better written in dot notation on line: 845 at character: 125
script: (W040) Possible strict violation on line: 943 at character: 29
script: (W040) Possible strict violation on line: 944 at character: 29
script: (W040) Possible strict violation on line: 950 at character: 11
script: (W004) 'i' is already defined on line: 1415 at character: 20
script: (W004) 'channelName' is already defined on line: 1422 at character: 33
script: (W116) Expected ':' and instead saw 'message' on line: 1550 at character: 15
script: (E020) Expected '}' to match '{' from line 1550 and instead saw 'type' on line: 1550 at character: 36
script: (E024) Unexpected '\' on line: 1550 at character: 41
script: (E031) Bad assignment on line: 1550 at character: 40
script: (W116) Expected ')' and instead saw 'buttons' on line: 1551 at character: 13
script: (W033) Missing semicolon on line: 1551 at character: 22
script: (E020) Expected '}' to match '{' from line 1549 and instead saw ':' on line: 1551 at character: 25
script: (W116) Expected ')' and instead saw '{' on line: 1551 at character: 27
script: (W033) Missing semicolon on line: 1551 at character: 28
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1552 at character: 17
script: (W033) Missing semicolon on line: 1552 at character: 25
script: (E020) Expected '}' to match '{' from line 18 and instead saw ':' on line: 1552 at character: 32
script: (E020) Expected ')' to match '(' from line 18 and instead saw '{' on line: 1552 at character: 34
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1552 at character: 34
script: (W033) Missing semicolon on line: 1552 at character: 35
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1553 at character: 21
script: (W033) Missing semicolon on line: 1553 at character: 28
script: (E041) Unrecoverable syntax error. (96% scanned) on line: 1553 at character: 33

**Comment by edvordo** [comment]
Hello! Thanks for the report. It seems I've messed up some commits while trying other stuff out.
The issue should be fixed now, please reinstall ToA :)

Side note: most of those were just hints (nothing to negatively impact the script itself), I chose to ignore for the time being. They have been fixed now :)
