### ISSUE TITLE
Reversed chat scrolls to top when clicking new tab.

### ISSUE THREAD

**Issue by kurosnow** [edvordo/TabsOfAvabur#3]
As title says, instead of scrolling to the bottom when you switch tabs, it scrolls to the top as if you had your chat normal. Quality of life thing, and forced me to switch back to standard chat because I don't want to have to scroll to the bottom every time I click another tab.

**Comment by edvordo** [comment]
This QoL is already implemented as mentioned in [FAQ](https://github.com/edvordo/TabsOfAvabur/wiki/FAQ).

If it doesn't seem to work for you, load the town hall, which should update the internal setting and subsequently make the preview window preserve your reversed chat option.

In case it would not, try turning off and on again the reversed chat option in Preferences and this will definitely update it, I just tried. :)
