### ISSUE TITLE
Naming a group after a channel breaks the channel.

### ISSUE THREAD

**Issue by kurosnow** [edvordo/TabsOfAvabur#4]
Named a group Main after the main chat, and then it wouldn't change the channel to main when clicking on the tab. Refreshing made me lose the game's main channel until I deleted the group.

**Comment by edvordo** [comment]
The channel detection system is not perfect, I know that.

There are fair few more issues with it I know of, naming a group after an existing channel is a known one. I won't fix this as it's easily fixable by naming the grouped tab something different, in your case for example `Main++`.
