### ISSUE TITLE
Chat direction is not respected

### ISSUE THREAD

**Issue by edvordo** [edvordo/TabsOfAvabur#5]
This is due to how I detected the chat order previously, which could have been done via inspecting Ajax responses. Now that everything is via WebSockets, it's not as simple,

Two was to solve this that come to my mind:
1. require the [RoA-WSHookUp](https://github.com/edvordo/RoA-WSHookUp) script and listen for `roa-ws:login_info`
  **Pro:** Fairly easy solution for me
  **Con:** Requires an extra script (albeit posibly usefull one) installed
2. Add an extra option to ToA to set chat direction
  **Pro:** Would be an internal script setting, so even if game changed output, script would still work
  **Con:** Won't be set automatically by user in-game preference and would require the player the to do this extra step

Please discuss which was would you be okay with :) I'm okay with both.

PS: If you have any other idea how to do this, feel free to suggest it in this issue.

**Comment by davidmcclelland** [comment]
Reversed chat is heresy. But for real, why not just look at the HTML element in the settings page that displays it. I believe it's always in the DOM. It's a little hacky, but probably simpler than both of these options.

**Comment by edvordo** [comment]
I'll have to check whether it's there on page load. If it is, this could work.
