### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by Mezandria** [edvordo/TabsOfAvabur#6]
I'm using google chrome. For the last week-two weeks, tabs of avabur isn't working. I'll click on the tab and the 'unread messages' number will disappear but it won't switch over to the channel tab, it will stay on the same channel no matter what tab I click on. If I refresh it fixes the problem for a short while (I can switch between tab channels) but if I leave it for a short time it will again get stuck. 

I haven't determined how long before it gets stuck or if something triggers it, but it seems to be within about 10 minutes. Which can get annoying if I have to refresh the page and lose actions just to look at another channel page. I haven't changed anything on my end that I know of.

**Comment by edvordo** [comment]
Get back to me or someone in the UserScripts channel ingame.

Although, I'm not sure how much can we help, when noone else is experiencing this issue, we will try.

**Comment by edvordo** [comment]
Probably resolved in #7

**Comment by edvordo** [comment]
Confirmed [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=961199). Wait for chrome to update.

Closing.
